name: login_register_app
description: tech administrator movil.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter 
  http: ^1.3.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  spider: ^4.2.2
  google_fonts: ^5.0.0
  cached_network_image: ^3.2.3
  jwt_decoder: ^2.0.1
  flutter_launcher_icons: ^0.14.3
  supabase_flutter: ^2.2.3
  intl: 0.20.2
  flutter_phoenix: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
 android: true
 ios: true
 image_path: "assets/images/mecanico.png"

flutter:

  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/mecanico.png
    - assets/images/descarga.jpeg
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/5.jpg
